import {useState,FormEvent} from 'react'
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query'
import {Plus,Upload,Copy,Pencil} from 'lucide-react'
import {api,date} from './api'
import {Service,Source,Event} from './types'
import {Panel,ErrorBox,Empty,Loading,Badge} from './ui'

export function Services({services}:{services:Service[]}){
 const blank={name:'',description:'',importance:3,environment:'production',dependencies:[] as string[]}
 const [form,setForm]=useState(blank),[edit,setEdit]=useState<string|null>(null)
 const qc=useQueryClient()
 const save=useMutation({mutationFn:()=>api('/services'+(edit?'/'+edit:''),{method:edit?'PUT':'POST',body:JSON.stringify(form)}),onSuccess:()=>{qc.invalidateQueries();setForm(blank);setEdit(null)}})
 return <div className="two-columns"><Panel title="Карта сервисов"><p className="panel-intro">Зависимости определяют возможное влияние сбоя. Они не доказывают фактическую недоступность.</p>{services.length?services.map(s=><div className="service-card" key={s.id}><div className="flex-between"><h3>{s.name}</h3><button className="icon-button" aria-label={'Редактировать '+s.name} onClick={()=>{setEdit(s.id);setForm(s)}}><Pencil size={16}/></button></div><p>{s.description||'Описание не задано'}</p><div className="tags"><Badge value={s.environment}/><span>Важность {s.importance}/5</span></div><small>Зависит от: {s.dependencies.map(id=>services.find(s=>s.id===id)?.name).join(', ')||'зависимости не заданы'}</small></div>):<Empty>Добавьте первый сервис или загрузите демо</Empty>}</Panel><Panel title={edit?'Редактирование сервиса':'Новый сервис'}><form className="form" onSubmit={e=>{e.preventDefault();save.mutate()}}><label>Название<input required maxLength={100} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="volunteer-api"/></label><label>Назначение и влияние<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Что произойдёт, если сервис перестанет работать?"/></label><div className="form-row"><label>Окружение<input required value={form.environment} onChange={e=>setForm({...form,environment:e.target.value})}/></label><label>Важность<select value={form.importance} onChange={e=>setForm({...form,importance:Number(e.target.value)})}>{[1,2,3,4,5].map(v=><option key={v} value={v}>{v} / 5</option>)}</select></label></div><fieldset><legend>Зависимости</legend>{services.filter(s=>s.id!==edit).map(s=><label className="check" key={s.id}><input type="checkbox" checked={form.dependencies.includes(s.id)} onChange={e=>setForm({...form,dependencies:e.target.checked?[...form.dependencies,s.id]:form.dependencies.filter(id=>id!==s.id)})}/>{s.name}</label>)}</fieldset><ErrorBox error={save.error}/><button disabled={save.isPending} className="primary"><Plus size={16}/>{save.isPending?'Сохранение…':'Сохранить сервис'}</button>{edit&&<button type="button" className="secondary" onClick={()=>{setForm(blank);setEdit(null)}}>Отмена</button>}</form></Panel></div>
}

export function Sources({services}:{services:Service[]}){
 const qc=useQueryClient()
 const q=useQuery({queryKey:['sources'],queryFn:()=>api<Source[]>('/sources')})
 const [name,setName]=useState(''),[sid,setSid]=useState(''),[source,setSource]=useState(''),[file,setFile]=useState<File|null>(null)
 const create=useMutation({mutationFn:()=>api<Source>('/sources',{method:'POST',body:JSON.stringify({name,service_id:sid,kind:'http'})}),onSuccess:s=>{qc.invalidateQueries();setName('');setSource(s.id)}})
 const upload=useMutation({mutationFn:()=>{const body=new FormData();body.append('file',file!);return api<{accepted:number;duplicates:number;rejected:number;errors:{line:number;error:string}[]}>('/sources/'+source+'/upload',{method:'POST',body})},onSuccess:()=>qc.invalidateQueries()})
 return <><div className="two-columns"><Panel title="Подключённые источники"><ErrorBox error={q.error}/>{q.isPending?<Loading/>:q.data?.length?q.data.map(s=><div className="service-card" key={s.id}><div className="flex-between"><h3>{s.name}</h3><Badge value={s.state}/></div><small>{services.find(x=>x.id===s.service_id)?.name} · {date(s.last_received)}</small><small>Последнее время события: {date(s.last_event)}</small><p>Принято {s.accepted} · Дубликаты {s.duplicates} · Отклонено {s.rejected}</p><code className="endpoint">POST /api/ingest/{s.id}</code>{s.last_error&&<ErrorBox error={s.last_error}/>}</div>):<Empty>Источники ещё не подключены</Empty>}</Panel><div className="stack"><Panel title="Добавить HTTP-источник"><form className="form" onSubmit={e=>{e.preventDefault();create.mutate()}}><label>Название<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Vector · API production"/></label><label>Сервис<select required value={sid} onChange={e=>setSid(e.target.value)}><option value="">Выберите сервис</option>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><button className="primary" disabled={create.isPending||!services.length}>Создать источник</button><ErrorBox error={create.error}/></form></Panel><Panel title="Загрузить логи"><form className="form" onSubmit={e=>{e.preventDefault();upload.mutate()}}><label>Источник<select required value={source} onChange={e=>setSource(e.target.value)}><option value="">Выберите источник</option>{q.data?.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="upload-zone"><Upload size={23}/><b>JSONL или Nginx access.log</b><small>UTF-8 · до 5 MiB · до 2000 строк</small><input type="file" required accept=".jsonl,.log,.txt,.json" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="primary" disabled={upload.isPending||!file||!source}>{upload.isPending?'Обработка…':'Загрузить и проанализировать'}</button><ErrorBox error={upload.error}/>{upload.data&&<div className="notice">Принято: {upload.data.accepted}; дубликаты: {upload.data.duplicates}; отклонено: {upload.data.rejected}{upload.data.errors.map(e=><p key={e.line}>Строка {e.line}: {e.error}</p>)}</div>}</form></Panel></div></div><Panel title="Постоянный приём через Vector"><p className="panel-intro">Укажите ID источника в VECTOR_SOURCE_ID файла .env и выполните docker compose up -d vector. Vector читает demo/logs и хранит буфер на диске. Новые данные появятся автоматически.</p><pre>{'POST /api/ingest/<source-id>\nAuthorization: Bearer <API_TOKEN>\nContent-Type: application/x-ndjson\n\n{"event_id":"unique-123","timestamp":"2026-10-03T12:00:00Z","status":503,"path":"/requests"}'}</pre><p className="panel-intro">Сохраняйте event_id при повторной доставке. Без него одинаковые нормализованные события одного источника считаются дубликатами. Ответ содержит ошибки отдельных строк: исправьте их и отправьте повторно.</p></Panel></>
}

export function Events({services}:{services:Service[]}){
 const [service,setService]=useState('')
 const q=useQuery({queryKey:['events',service],queryFn:()=>api<Event[]>('/events?limit=200'+(service?'&service_id='+service:''))})
 return <Panel title="Последние 200 событий" extra={<select aria-label="Сервис" value={service} onChange={e=>setService(e.target.value)}><option value="">Все сервисы</option>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>}><ErrorBox error={q.error}/>{q.isPending?<Loading/>:q.data?.length?<div className="table-scroll"><table><thead><tr><th>Время события</th><th>Сервис</th><th>Тип / код</th><th>Контекст</th><th>Данные</th></tr></thead><tbody>{q.data.map(e=><tr key={e.id}><td>{date(e.timestamp)}</td><td>{services.find(s=>s.id===e.service_id)?.name}</td><td><Badge value={String(e.data.event||e.data.status||'log')}/></td><td className="mono">{String(e.data.path||e.data.message||e.data.user||'—')}</td><td>{e.data.synthetic?<Badge value="DEMO"/>:'Реальные'}</td></tr>)}</tbody></table></div>:<Empty>Событий пока нет</Empty>}</Panel>
}
