import {useState,FormEvent} from 'react'
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query'
import {Plus,Upload,Copy,Pencil} from 'lucide-react'
import {api,date} from './api'
import {Service,Source,Event} from './types'
import {Panel,ErrorBox,Empty,Loading,Badge} from './ui'

export function Services({services}:{services:Service[]}){
 const blank={name:'',description:'',importance:3,environment:'production',dependencies:[] as string[]}
 const [form,setForm]=useState(blank),[edit,setEdit]=useState<string|null>(null)
 const qc=useQueryClient()
 const save=useMutation({mutationFn:()=>api('/services'+(edit?'/'+edit:''),{method:edit?'PUT':'POST',body:JSON.stringify(form)}),onSuccess:()=>{qc.invalidateQueries();setForm(blank);setEdit(null)}})
 return <div className="two-columns"><Panel title="Service map"><p className="panel-intro">Dependencies define potential outage impact. They do not prove actual unavailability.</p>{services.length?services.map(s=><div className="service-card" key={s.id}><div className="flex-between"><h3>{s.name}</h3><button className="icon-button" aria-label={'Edit '+s.name} onClick={()=>{setEdit(s.id);setForm(s)}}><Pencil size={16}/></button></div><p>{s.description||'No description provided'}</p><div className="tags"><Badge value={s.environment}/><span>Importance {s.importance}/5</span></div><small>Depends on: {s.dependencies.map(id=>services.find(s=>s.id===id)?.name).join(', ')||'no dependencies set'}</small></div>):<Empty>Add the first service or load the demo</Empty>}</Panel><Panel title={edit?'Edit service':'New service'}><form className="form" onSubmit={e=>{e.preventDefault();save.mutate()}}><label>Name<input required maxLength={100} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="volunteer-api"/></label><label>Purpose and impact<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="What happens if this service stops working?"/></label><div className="form-row"><label>Environment<input required value={form.environment} onChange={e=>setForm({...form,environment:e.target.value})}/></label><label>Importance<select value={form.importance} onChange={e=>setForm({...form,importance:Number(e.target.value)})}>{[1,2,3,4,5].map(v=><option key={v} value={v}>{v} / 5</option>)}</select></label></div><fieldset><legend>Dependencies</legend>{services.filter(s=>s.id!==edit).map(s=><label className="check" key={s.id}><input type="checkbox" checked={form.dependencies.includes(s.id)} onChange={e=>setForm({...form,dependencies:e.target.checked?[...form.dependencies,s.id]:form.dependencies.filter(id=>id!==s.id)})}/>{s.name}</label>)}</fieldset><ErrorBox error={save.error}/><button disabled={save.isPending} className="primary"><Plus size={16}/>{save.isPending?'Saving…':'Save service'}</button>{edit&&<button type="button" className="secondary" onClick={()=>{setForm(blank);setEdit(null)}}>Cancel</button>}</form></Panel></div>
}

export function Sources({services}:{services:Service[]}){
 const qc=useQueryClient()
 const q=useQuery({queryKey:['sources'],queryFn:()=>api<Source[]>('/sources')})
 const [name,setName]=useState(''),[sid,setSid]=useState(''),[source,setSource]=useState(''),[file,setFile]=useState<File|null>(null)
 const create=useMutation({mutationFn:()=>api<Source>('/sources',{method:'POST',body:JSON.stringify({name,service_id:sid,kind:'http'})}),onSuccess:s=>{qc.invalidateQueries();setName('');setSource(s.id)}})
 const upload=useMutation({mutationFn:()=>{const body=new FormData();body.append('file',file!);return api<{accepted:number;duplicates:number;rejected:number;errors:{line:number;error:string}[]}>('/sources/'+source+'/upload',{method:'POST',body})},onSuccess:()=>qc.invalidateQueries()})
 return <><div className="two-columns"><Panel title="Connected sources"><ErrorBox error={q.error}/>{q.isPending?<Loading/>:q.data?.length?q.data.map(s=><div className="service-card" key={s.id}><div className="flex-between"><h3>{s.name}</h3><Badge value={s.state}/></div><small>{services.find(x=>x.id===s.service_id)?.name} · {date(s.last_received)}</small><small>Latest event time: {date(s.last_event)}</small><p>Accepted {s.accepted} · Duplicates {s.duplicates} · Rejected {s.rejected}</p><code className="endpoint">POST /api/ingest/{s.id}</code>{s.last_error&&<ErrorBox error={s.last_error}/>}</div>):<Empty>No sources connected yet</Empty>}</Panel><div className="stack"><Panel title="Add HTTP source"><form className="form" onSubmit={e=>{e.preventDefault();create.mutate()}}><label>Name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Vector · API production"/></label><label>Service<select required value={sid} onChange={e=>setSid(e.target.value)}><option value="">Select a service</option>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><button className="primary" disabled={create.isPending||!services.length}>Create source</button><ErrorBox error={create.error}/></form></Panel><Panel title="Upload logs"><form className="form" onSubmit={e=>{e.preventDefault();upload.mutate()}}><label>Source<select required value={source} onChange={e=>setSource(e.target.value)}><option value="">Select a source</option>{q.data?.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="upload-zone"><Upload size={23}/><b>JSONL or Nginx access.log</b><small>UTF-8 · up to 5 MiB · up to 2000 lines</small><input type="file" required accept=".jsonl,.log,.txt,.json" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="primary" disabled={upload.isPending||!file||!source}>{upload.isPending?'Processing…':'Upload and analyze'}</button><ErrorBox error={upload.error}/>{upload.data&&<div className="notice">Accepted: {upload.data.accepted}; duplicates: {upload.data.duplicates}; rejected: {upload.data.rejected}{upload.data.errors.map(e=><p key={e.line}>Line {e.line}: {e.error}</p>)}</div>}</form></Panel></div></div><Panel title="Continuous intake through Vector"><p className="panel-intro">Set the source ID in VECTOR_SOURCE_ID in .env and run docker compose up -d vector. Vector reads demo/logs and keeps its buffer on disk. New data will appear automatically.</p><pre>{'POST /api/ingest/<source-id>\nAuthorization: Bearer <API_TOKEN>\nContent-Type: application/x-ndjson\n\n{"event_id":"unique-123","timestamp":"2026-10-03T12:00:00Z","status":503,"path":"/requests"}'}</pre><p className="panel-intro">Keep event_id on redelivery. Without it, identical normalized events from the same source are treated as duplicates. The response contains per-line errors: fix them and resend.</p></Panel></>
}

export function Events({services}:{services:Service[]}){
 const [service,setService]=useState('')
 const q=useQuery({queryKey:['events',service],queryFn:()=>api<Event[]>('/events?limit=200'+(service?'&service_id='+service:''))})
 return <Panel title="Last 200 events" extra={<select aria-label="Service" value={service} onChange={e=>setService(e.target.value)}><option value="">All services</option>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>}><ErrorBox error={q.error}/>{q.isPending?<Loading/>:q.data?.length?<div className="table-scroll"><table><thead><tr><th>Event time</th><th>Service</th><th>Type / code</th><th>Context</th><th>Data</th></tr></thead><tbody>{q.data.map(e=><tr key={e.id}><td>{date(e.timestamp)}</td><td>{services.find(s=>s.id===e.service_id)?.name}</td><td><Badge value={String(e.data.event||e.data.status||'log')}/></td><td className="mono">{String(e.data.path||e.data.message||e.data.user||'—')}</td><td>{e.data.synthetic?<Badge value="DEMO"/>:'Real'}</td></tr>)}</tbody></table></div>:<Empty>No events yet</Empty>}</Panel>
}
