import {useState} from 'react'
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query'
import {Upload,ArrowLeft,RefreshCw} from 'lucide-react'
import {api,date} from './api'
import {Service,Scan,Deployment} from './types'
import {Panel,Badge,Empty,Loading,ErrorBox} from './ui'
export function Images({services}:{services:Service[]}){
 const qc=useQueryClient()
 const q=useQuery({queryKey:['scans'],queryFn:()=>api<Scan[]>('/scans')})
 const deployments=useQuery({queryKey:['deployments'],queryFn:()=>api<Deployment[]>('/deployments')})
 const [selected,setSelected]=useState(''),[file,setFile]=useState<File|null>(null)
 const [form,setForm]=useState({service_id:'',scan_id:'',started_at:'',ended_at:'',confirmation:'unverified',evidence:''})
 const detail=useQuery({queryKey:['scan',selected],queryFn:()=>api<Scan>('/scans/'+selected),enabled:!!selected})
 const upload=useMutation({mutationFn:()=>{const body=new FormData();body.append('file',file!);return api<Scan>('/scans',{method:'POST',body})},onSuccess:s=>{qc.invalidateQueries();setSelected(s.id)}})
 const retry=useMutation({mutationFn:(id:string)=>api('/scans/'+id+'/retry',{method:'POST'}),onSuccess:()=>qc.invalidateQueries()})
 const link=useMutation({mutationFn:()=>api('/deployments',{method:'POST',body:JSON.stringify({...form,started_at:new Date(form.started_at).toISOString(),ended_at:form.ended_at?new Date(form.ended_at).toISOString():null})}),onSuccess:()=>qc.invalidateQueries()})
 const scan=detail.data
 return <><div className="notice">Образ анализируется в отдельном worker и никогда не запускается. Архив docker save не предоставляет runtime-логи. CVE не является доказательством взлома.</div><div className="two-columns"><Panel title="Сканирования Trivy"><ErrorBox error={q.error||retry.error}/>{q.isPending?<Loading/>:q.data?.length?q.data.map(s=><div className="scan-row" key={s.id}><button onClick={()=>setSelected(s.id)}><b>{s.filename}</b><small>{date(s.created_at)}</small><Badge value={s.status}/>{s.summary&&<p>{s.summary.vulnerabilities} CVE · {s.summary.components} компонентов · {s.summary.secrets} потенциальных секретов</p>}</button>{s.error&&<ErrorBox error={s.error}/>}<small className="mono">SHA256 {s.digest.slice(0,24)}…</small>{s.status==='failed'&&<button className="secondary" disabled={retry.isPending} onClick={()=>retry.mutate(s.id)}><RefreshCw size={14}/>Повторить</button>}</div>):<Empty>Образы ещё не загружены</Empty>}</Panel><Panel title="Добавить образ"><form className="form" onSubmit={e=>{e.preventDefault();upload.mutate()}}><label className="upload-zone"><Upload size={26}/><b>Архив Docker-образа</b><small>docker save image:tag -o image.tar · до 512 MiB</small><input type="file" accept=".tar" required onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="primary" disabled={!file||upload.isPending}>{upload.isPending?'Загрузка и проверка архива…':'Загрузить и сканировать'}</button><ErrorBox error={upload.error}/></form><p className="muted">При первом сканировании Trivy загружает базу уязвимостей. При недоступности worker задача остаётся в очереди; ошибки и повторные попытки отображаются здесь.</p></Panel></div>
 {selected&&<Panel title="Результат анализа" extra={<button className="back" onClick={()=>setSelected('')}>Закрыть</button>}><ErrorBox error={detail.error}/>{detail.isPending?<Loading/>:scan&&<><div className="flex-between"><h3>{scan.filename}</h3><Badge value={scan.status}/></div><ErrorBox error={scan.error}/>{scan.result?<><div className="scan-totals"><span><b>{scan.result.summary?.vulnerabilities}</b> уязвимостей</span><span><b>{scan.result.summary?.components}</b> компонентов</span><span><b>{scan.result.summary?.secrets}</b> потенциальных секретов</span></div>{scan.result.limitations.map(l=><p className="muted" key={l}>{l}</p>)}<h3 className="section-label">Уязвимости</h3>{scan.result.vulnerabilities.length?<div className="table-scroll"><table><thead><tr><th>CVE</th><th>Уровень</th><th>Компонент</th><th>Установлено</th><th>Исправлено</th></tr></thead><tbody>{scan.result.vulnerabilities.map((v,n)=><tr key={n}><td>{/^https:\/\//.test(v.PrimaryURL||'')?<a href={v.PrimaryURL} target="_blank" rel="noreferrer">{v.VulnerabilityID}</a>:v.VulnerabilityID}</td><td><Badge value={v.Severity}/></td><td>{v.PkgName}</td><td>{v.InstalledVersion}</td><td>{v.FixedVersion||'Нет данных'}</td></tr>)}</tbody></table></div>:<Empty>Известные уязвимости не найдены в пределах покрытия Trivy</Empty>}<details><summary>Компоненты ({scan.result.components.length})</summary><div className="table-scroll"><table><tbody>{scan.result.components.map((p,n)=><tr key={n}><td>{p.name}</td><td>{p.version}</td><td>{p.target}</td></tr>)}</tbody></table></div></details><details><summary>Потенциальные секреты ({scan.result.secrets.length})</summary>{scan.result.secrets.map((s,n)=><div className="service-card" key={n}><Badge value={s.severity}/><b>{s.title}</b><p>{s.target}:{s.line}</p><small>Значение скрыто. Подтвердите находку, отзовите и замените секрет при необходимости.</small></div>)}</details></>:<Empty>Результат пока недоступен. Состояние обновляется автоматически.</Empty>}</>}</Panel>}
 <div className="two-columns"><Panel title="Связать образ с развёртыванием"><form className="form" onSubmit={e=>{e.preventDefault();link.mutate()}}><label>Сервис<select required value={form.service_id} onChange={e=>setForm({...form,service_id:e.target.value})}><option value="">Выберите сервис</option>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Образ<select required value={form.scan_id} onChange={e=>setForm({...form,scan_id:e.target.value})}><option value="">Выберите образ</option>{q.data?.map(s=><option key={s.id} value={s.id}>{s.filename} · {s.digest.slice(0,10)}</option>)}</select></label><div className="form-row"><label>Начало (местное время)<input type="datetime-local" required value={form.started_at} onChange={e=>setForm({...form,started_at:e.target.value})}/></label><label>Конец (необязательно)<input type="datetime-local" value={form.ended_at} onChange={e=>setForm({...form,ended_at:e.target.value})}/></label></div><label>Подтверждённость<select value={form.confirmation} onChange={e=>setForm({...form,confirmation:e.target.value})}><option value="unverified">Не подтверждено</option><option value="operator_confirmed">Подтверждено оператором</option></select></label><label>Доказательство развёртывания<textarea required={form.confirmation==='operator_confirmed'} value={form.evidence} onChange={e=>setForm({...form,evidence:e.target.value})} placeholder="Digest из deployment, ссылка на CI или основание предположения"/></label><ErrorBox error={link.error}/>{link.isSuccess&&<div className="notice">Связь сохранена</div>}<button className="primary" disabled={link.isPending}>Сохранить связь</button></form></Panel><Panel title="Периоды развёртывания"><ErrorBox error={deployments.error}/>{deployments.data?.length?deployments.data.map(d=><div className="service-card" key={d.id}><h3>{services.find(s=>s.id===d.service_id)?.name}</h3><p>{q.data?.find(s=>s.id===d.scan_id)?.filename||d.scan_id}</p><Badge value={d.confirmation}/><p>{date(d.started_at)} — {d.ended_at?date(d.ended_at):'текущее'}</p><small>{d.evidence||'Доказательство не предоставлено'}</small></div>):<Empty>Связи образов с сервисами не установлены</Empty>}</Panel></div></>
}
