import {useState} from 'react'
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query'
import {Upload,ArrowLeft,RefreshCw} from 'lucide-react'
import {api,date} from './api'
import {Service,Scan,Deployment} from './types'
import {Panel,Badge,Empty,Loading,ErrorBox} from './ui'
export function Images({services}:{services:Service[]}){
 const qc=useQueryClient()
 const q=useQuery({queryKey:['scans'],queryFn:()=>api<Scan[]>('/scans')})
 const deployments=useQuery({queryKey:['deployments'],queryFn:()=>api<Deployment[]>('/deployments')})
 const [selected,setSelected]=useState(''),[file,setFile]=useState<File|null>(null)
 const [form,setForm]=useState({service_id:'',scan_id:'',started_at:'',ended_at:'',confirmation:'unverified',evidence:''})
 const detail=useQuery({queryKey:['scan',selected],queryFn:()=>api<Scan>('/scans/'+selected),enabled:!!selected})
 const upload=useMutation({mutationFn:()=>{const body=new FormData();body.append('file',file!);return api<Scan>('/scans',{method:'POST',body})},onSuccess:s=>{qc.invalidateQueries();setSelected(s.id)}})
 const retry=useMutation({mutationFn:(id:string)=>api('/scans/'+id+'/retry',{method:'POST'}),onSuccess:()=>qc.invalidateQueries()})
 const link=useMutation({mutationFn:()=>api('/deployments',{method:'POST',body:JSON.stringify({...form,started_at:new Date(form.started_at).toISOString(),ended_at:form.ended_at?new Date(form.ended_at).toISOString():null})}),onSuccess:()=>qc.invalidateQueries()})
 const scan=detail.data
 return <><div className="notice">The image is analyzed in a separate worker and is never executed. A docker save archive does not provide runtime logs. A CVE is not evidence of compromise.</div><div className="two-columns"><Panel title="Trivy scans"><ErrorBox error={q.error||retry.error}/>{q.isPending?<Loading/>:q.data?.length?q.data.map(s=><div className="scan-row" key={s.id}><button onClick={()=>setSelected(s.id)}><b>{s.filename}</b><small>{date(s.created_at)}</small><Badge value={s.status}/>{s.summary&&<p>{s.summary.vulnerabilities} CVE · {s.summary.components} components · {s.summary.secrets} potential secrets</p>}</button>{s.error&&<ErrorBox error={s.error}/>}<small className="mono">SHA256 {s.digest.slice(0,24)}…</small>{s.status==='failed'&&<button className="secondary" disabled={retry.isPending} onClick={()=>retry.mutate(s.id)}><RefreshCw size={14}/>Retry</button>}</div>):<Empty>No images uploaded yet</Empty>}</Panel><Panel title="Add image"><form className="form" onSubmit={e=>{e.preventDefault();upload.mutate()}}><label className="upload-zone"><Upload size={26}/><b>Docker image archive</b><small>docker save image:tag -o image.tar · up to 512 MiB</small><input type="file" accept=".tar" required onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="primary" disabled={!file||upload.isPending}>{upload.isPending?'Uploading and validating archive…':'Upload and scan'}</button><ErrorBox error={upload.error}/></form><p className="muted">On the first scan, Trivy downloads its vulnerability database. If the worker is unavailable, the job remains queued; errors and retries are shown here.</p></Panel></div>
 {selected&&<Panel title="Analysis result" extra={<button className="back" onClick={()=>setSelected('')}>Close</button>}><ErrorBox error={detail.error}/>{detail.isPending?<Loading/>:scan&&<><div className="flex-between"><h3>{scan.filename}</h3><Badge value={scan.status}/></div><ErrorBox error={scan.error}/>{scan.result?<><div className="scan-totals"><span><b>{scan.result.summary?.vulnerabilities}</b> vulnerabilities</span><span><b>{scan.result.summary?.components}</b> components</span><span><b>{scan.result.summary?.secrets}</b> potential secrets</span></div>{scan.result.limitations.map(l=><p className="muted" key={l}>{l}</p>)}<h3 className="section-label">Vulnerabilities</h3>{scan.result.vulnerabilities.length?<div className="table-scroll"><table><thead><tr><th>CVE</th><th>Level</th><th>Component</th><th>Installed</th><th>Fixed</th></tr></thead><tbody>{scan.result.vulnerabilities.map((v,n)=><tr key={n}><td>{/^https:\/\//.test(v.PrimaryURL||'')?<a href={v.PrimaryURL} target="_blank" rel="noreferrer">{v.VulnerabilityID}</a>:v.VulnerabilityID}</td><td><Badge value={v.Severity}/></td><td>{v.PkgName}</td><td>{v.InstalledVersion}</td><td>{v.FixedVersion||'n/a'}</td></tr>)}</tbody></table></div>:<Empty>No known vulnerabilities found within Trivy coverage</Empty>}<details><summary>Components ({scan.result.components.length})</summary><div className="table-scroll"><table><tbody>{scan.result.components.map((p,n)=><tr key={n}><td>{p.name}</td><td>{p.version}</td><td>{p.target}</td></tr>)}</tbody></table></div></details><details><summary>Potential secrets ({scan.result.secrets.length})</summary>{scan.result.secrets.map((s,n)=><div className="service-card" key={n}><Badge value={s.severity}/><b>{s.title}</b><p>{s.target}:{s.line}</p><small>Value hidden. Confirm the finding, then revoke and replace the secret if needed.</small></div>)}</details></>:<Empty>Result is not available yet. Status updates automatically.</Empty>}</>}</Panel>}
 <div className="two-columns"><Panel title="Link image to deployment"><form className="form" onSubmit={e=>{e.preventDefault();link.mutate()}}><label>Service<select required value={form.service_id} onChange={e=>setForm({...form,service_id:e.target.value})}><option value="">Select a service</option>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Image<select required value={form.scan_id} onChange={e=>setForm({...form,scan_id:e.target.value})}><option value="">Select an image</option>{q.data?.map(s=><option key={s.id} value={s.id}>{s.filename} · {s.digest.slice(0,10)}</option>)}</select></label><div className="form-row"><label>Start (local time)<input type="datetime-local" required value={form.started_at} onChange={e=>setForm({...form,started_at:e.target.value})}/></label><label>End (optional)<input type="datetime-local" value={form.ended_at} onChange={e=>setForm({...form,ended_at:e.target.value})}/></label></div><label>Confirmation<select value={form.confirmation} onChange={e=>setForm({...form,confirmation:e.target.value})}><option value="unverified">Unverified</option><option value="operator_confirmed">Operator confirmed</option></select></label><label>Deployment evidence<textarea required={form.confirmation==='operator_confirmed'} value={form.evidence} onChange={e=>setForm({...form,evidence:e.target.value})} placeholder="Deployment digest, CI link, or rationale"/></label><ErrorBox error={link.error}/>{link.isSuccess&&<div className="notice">Link saved</div>}<button className="primary" disabled={link.isPending}>Save link</button></form></Panel><Panel title="Deployment periods"><ErrorBox error={deployments.error}/>{deployments.data?.length?deployments.data.map(d=><div className="service-card" key={d.id}><h3>{services.find(s=>s.id===d.service_id)?.name}</h3><p>{q.data?.find(s=>s.id===d.scan_id)?.filename||d.scan_id}</p><Badge value={d.confirmation}/><p>{date(d.started_at)} — {d.ended_at?date(d.ended_at):'current'}</p><small>{d.evidence||'No evidence provided'}</small></div>):<Empty>No image-to-service links configured</Empty>}</Panel></div></>
}
