const {chromium}=require('playwright');
const path=require('path');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'chrome'});
 const page=await browser.newPage({viewport:{width:1440,height:1100}});
 const errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.WEB_URL||'http://localhost:18080');
 await page.getByLabel('API-токен').fill(process.env.API_TOKEN||'local-development-token');
 await page.getByRole('button',{name:'Открыть рабочее пространство'}).click();
 await page.getByRole('heading',{name:'Обзор',exact:true}).waitFor();
 await page.getByRole('heading',{name:'Поток событий'}).waitFor();
 await page.screenshot({path:path.join(__dirname,'../test-results/dashboard.png'),fullPage:true});
 await page.getByRole('button',{name:'Инциденты',exact:true}).click();
 await page.getByRole('button').filter({hasText:'Рост / высокий уровень ошибок API'}).first().click();
 await page.getByRole('heading',{name:'Доказательства и хронология'}).waitFor();
 await page.getByLabel('Что проверили или изменили').fill('Browser smoke: проверена доступность API; требуется наблюдение.');
 await page.getByRole('button',{name:'Сохранить действие',exact:true}).click();
 await page.getByText('Browser smoke: проверена доступность API; требуется наблюдение.',{exact:false}).waitFor();
 await page.getByRole('button',{name:'Проверить результат по новым логам'}).click();
 await page.getByText('insufficient:',{exact:false}).first().waitFor();
 await page.screenshot({path:path.join(__dirname,'../test-results/incident.png'),fullPage:true});
 await page.getByRole('button',{name:'Сервисы',exact:true}).click();
 await page.getByLabel('Название',{exact:true}).fill('browser-smoke-'+Date.now());
 await page.getByLabel('Назначение и влияние').fill('Synthetic browser test service');
 await page.getByRole('button',{name:'Сохранить сервис'}).click();
 await page.getByText('Synthetic browser test service',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Источники',exact:true}).click();
 await page.getByRole('heading',{name:'Подключённые источники'}).waitFor();
 await page.getByRole('button',{name:'Образы',exact:true}).click();
 await page.getByRole('heading',{name:'Сканирования Trivy'}).waitFor();
 await page.getByRole('button',{name:'Журнал событий',exact:true}).click();
 await page.getByRole('heading',{name:'Последние 200 событий'}).waitFor();
 await page.getByRole('button',{name:'Обзор',exact:true}).click();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:path.join(__dirname,'../test-results/mobile.png'),fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false,'mobile horizontal overflow');
 assert.deepEqual(errors,[],'browser JS errors');
 await browser.close();
 console.log('PASS: login, dashboard, incident evidence, operator action, verification, service create, sources, images, events, mobile width; no JavaScript errors');
})().catch(e=>{console.error(e);process.exit(1)});
