const {chromium}=require('playwright');
const path=require('path');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'chrome'});
 const page=await browser.newPage({viewport:{width:1440,height:1100}});
 const errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.WEB_URL||'http://localhost:18080');
 await page.getByLabel('API token').fill(process.env.API_TOKEN||'local-development-token');
 await page.getByRole('button',{name:'Open workspace'}).click();
 await page.getByRole('heading',{name:'Overview',exact:true}).waitFor();
 await page.getByRole('heading',{name:'Event stream'}).waitFor();
 await page.screenshot({path:path.join(__dirname,'../test-results/dashboard.png'),fullPage:true});
 await page.getByRole('button',{name:'Incidents',exact:true}).click();
 await page.getByRole('button').filter({hasText:'Rising or high API error rate'}).first().click();
 await page.getByRole('heading',{name:'Evidence and timeline'}).waitFor();
 await page.getByLabel('What you checked or changed').fill('Browser smoke: API availability checked; monitoring required.');
 await page.getByRole('button',{name:'Save action',exact:true}).click();
 await page.getByText('Browser smoke: API availability checked; monitoring required.',{exact:false}).waitFor();
 await page.getByRole('button',{name:'Verify outcome from new logs'}).click();
 await page.getByText('insufficient:',{exact:false}).first().waitFor();
 await page.screenshot({path:path.join(__dirname,'../test-results/incident.png'),fullPage:true});
 await page.getByRole('button',{name:'Services',exact:true}).click();
 await page.getByLabel('Name',{exact:true}).fill('browser-smoke-'+Date.now());
 await page.getByLabel('Purpose and impact').fill('Synthetic browser test service');
 await page.getByRole('button',{name:'Save service'}).click();
 await page.getByText('Synthetic browser test service',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Sources',exact:true}).click();
 await page.getByRole('heading',{name:'Connected sources'}).waitFor();
 await page.getByRole('button',{name:'Images',exact:true}).click();
 await page.getByRole('heading',{name:'Trivy scans'}).waitFor();
 await page.getByRole('button',{name:'Event log',exact:true}).click();
 await page.getByRole('heading',{name:'Last 200 events'}).waitFor();
 await page.getByRole('button',{name:'Overview',exact:true}).click();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:path.join(__dirname,'../test-results/mobile.png'),fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false,'mobile horizontal overflow');
 assert.deepEqual(errors,[],'browser JS errors');
 await browser.close();
 console.log('PASS: login, dashboard, incident evidence, operator action, verification, service create, sources, images, events, mobile width; no JavaScript errors');
})().catch(e=>{console.error(e);process.exit(1)});
