from pathlib import Path
p=Path("frontend/src/App.tsx")
s=p.read_text().replace("Dashboard,Incident,Service,Source", "Dashboard,Incident,Service,Source,Scan")
s=s.replace(" const sources=useQuery(", " const scans=useQuery({queryKey:['scans'],queryFn:()=>api<Scan[]>('/scans')})\n const sources=useQuery(")
s=s.replace('<div className="principle">','<Panel title="Latest image scans"><ErrorBox error={scans.error}/>{scans.data?.length?scans.data.slice(0,3).map(s=><div className="source-row" key={s.id}><div><b>{s.filename}</b><small>{s.summary?s.summary.vulnerabilities+" CVE · "+s.summary.components+" components · "+s.summary.secrets+" potential secrets":s.error||"Result not available yet"}</small></div><Badge value={s.status}/></div>):<Empty>Upload a docker save archive in Images</Empty>}</Panel>\n <div className="principle">')
p.write_text(s)
p=Path("backend/app/main.py")
s=p.read_text().replace('result.append(dict(row(x), state="error" if x.last_error else state))','latest = db.scalar(select(func.max(Event.timestamp)).where(Event.source_id == x.id))\n        result.append(dict(row(x), state="error" if x.last_error else state, last_event=latest))')
p.write_text(s)
p=Path("frontend/src/types.ts")
s=p.read_text().replace("last_received:string|null;", "last_received:string|null;last_event:string|null;")
p.write_text(s)
p=Path("frontend/src/DataPages.tsx")
s=p.read_text().replace('<p>Accepted {s.accepted}', '<small>Latest event time: {date(s.last_event)}</small><p>Accepted {s.accepted}')
p.write_text(s)
